name: Build & Test
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - uses: actions/checkout@v2

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Install Errcheck
        run: go install github.com/kisielk/errcheck@latest

      - name: Run Errcheck
        run: errcheck ./...
